# pyproject.toml

[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.pylint.master]
ignore-patterns = [
    "^__init__\\.py$",
    "requirements^.txt"
]

[tool.pylint.messages_control]
disable = [
    "C0103",  # invalid-name
    "C0111",  # missing-docstring
    "W0611",  # unused-import
    "E1101",  # no-member
    "R0902",  # Too many instance attributes
    "R0903",  # Too few public methods
    "line-too-long",
    "too-many-arguments"
]

[tool.pylint.format]
max-line-length = 100